namespace LPD.Compiler.Lexical
{
    public enum Symbols
    {
        SInicio = 0,
        SFim = 1,
        SProcedimento = 2,
        SFuncao = 3,
        SSe = 4,
        SEntao = 5,
        SSenao = 6,
        SEnquanto = 7,
        SFaca = 8,
        SAtribuicao = 9,
        SEscreva = 10,
        SLeia = 11,
        SVar = 12,
        SInteiro = 13,
        SBooleano = 14,
        SIdentificador = 15,
        SNumero = 16,
        SPonto = 17,
        SPontoVirgula = 18,
        SVirgula = 19,
        SAbreParenteses = 20,
        SFechaParenteses = 21,
        SMaior = 22,
        SMaiorIg = 23,
        SIg = 24,
        SMenor = 25,
        SMenorIg = 26,
        SDif = 27,
        SMais = 28,
        SMenos = 29,
        SMult = 30,
        SDiv = 31,
        SE = 32,
        SOu = 33,
        SNao = 34,
        SDoisPontos = 35,
        SPrograma = 36,
        SVerdadeiro = 37,
        SFalso = 38,
        None = 39
    }
}
